### ISSUE TITLE
Sometimes the objects does not resize properly when the window resizes.

### ISSUE THREAD

**Issue by Koshin-S-Hegde** [Koshin-S-Hegde/School-Project-trial-1#15]

**Comment by Koshin-S-Hegde** [comment]
@Koshin-S-Hegde I think I might have an idea about what is wrong.

**Comment by Koshin-S-Hegde** [comment]
My bad 17b73c78ed1609c267f207426f41e6f426e81080 was supposed to refer to this issue.

**Comment by LONEZAD** [comment]
we need to fix this.
